### ISSUE TITLE
Service for daemons can't work with `self_hostname` set to 127.0.0.1

### ISSUE THREAD

**Issue by skandragon** [Chia-Network/chia-operator#122]
The default `self_hostname` value is `127.0.0.1`, which the daemon uses to select its listen address.  This is probably good, except when exposing the daemon as a service in any way.  For instance, the daemon services do nothing currently.

**Comment by skandragon** [comment]
Another possibility is to allow environment variables to be set, which would allow me to set `self_hostname` directly.

**Comment by Starttoaster** [comment]
Thanks for the Issue! Yeah, I think for this it probably makes sense to add a new option to custom resources, under `.spec.chia.selfHostname`. I'm hesitant on adding the ability to set custom env vars if there's not a better use case for it, ideally the operator manages those from the custom resource config.

**Comment by Starttoaster** [comment]
Would you prefer to see it default to `0.0.0.0`? Or do you think the current default of `127.0.0.1` is appropriate?

**Comment by Starttoaster** [comment]
The linked PR has been merged, I decided to keep it to a default of 127.0.0.1, staying in line with the chia-docker default.

This feature will be available in an upcoming release.

**Comment by Starttoaster** [comment]
Support for setting self_hostname was added in 0.7.0. Thanks for bringing this Issue!
